{% set name = 'crystalmapping' %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  # Uncomment the following line if the package is pure Python and the recipe
  # is exactly the same for all platforms. It is okay if the dependencies are
  # not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python
  # for more details.
  # noarch: python

  noarch: python
  number: {{ build_number }}
  string: "{{ [ build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '') ] | join('_') }}"
  script: "python -m pip install . -vv"

  requirements:
    host:
      - python
      - pip
    run:
      - trackpy==0.5.0
      - bluesky==1.6.7
      - databroker==1.2.3
      - databroker-pack==0.3.0
      - pyfai==0.20.0
      - fire

  test:
    # Some packages might need a `test/commands` key to check CLI.
    # List all the packages/modules that `run_test.py` imports.
    imports:
      - crystalmapping
      - crystalmapping.utils
    # Run your test commands here
  # Uncomment and fill in crystalmapping metadata
  #about:
  #  home: https://github.com/conda-forge/conda-smithy
  #  license: BSD-3-Clause
  #  license_family: BSD
  #  license_file: LICENSE

  # Uncomment the following if this will be on a forge
  # Remove these lines if this is only be used for CI
  #extra:
  #  recipe-maintainers:
  #    - BobaFett
  #    - LisaSimpson
