channels:
  # sources selects the channels to pull packages from, in order.
  sources:
    - defaults
    - nsls2forge
    - conda-forge
  # targets is a list of 2-lists, where the first element is the
  # channel to push to and the second element is the label on that channel
  targets:
    - [ "st3107", "main" ]
github:
  # name of the github organization
  user_or_org: st3107
  # repository name, usually filled in automatically
  repo_name: ""
  # branch name to execute on
  branch_name: main
clone_depth: 0
recipe_dir: recipe
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - build-locally.py
  - LICENSE
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows
  - __pycache__
