name: Test

on:
  - push
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - name: cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('etc/example-environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: test-env.yaml
          auto-update-conda: false
          auto-activate-base: false
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: install the package
        run: python -m pip install . --no-deps

      - name: run the tests and check for test coverage
        run: coverage run -m pytest

      - name: generate the test coverage report and upload it to codecov
        run: |
          coverage report -m
          codecov

      - name: check the code style
        run: flake8
